URL_LOGIN="server/mock/login.php"
URL_QUITSESSION="server/sessionQuit.php"
URL_GET_LOAN_RESPONSIBLES="server/mock/getResponsibles.php"
URL_INSERT_NEW_PRODUCT="server/mock/insertNewProduct.php"
URL_UPLOAD_CSV="server/mock/csvProductsUpload.php"
